### ISSUE TITLE
Making it easier to configure A/B tests

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-cdn-config#28]
Currently we have to copy-paste a lot of VCL to configure an A/B test (see https://github.com/alphagov/govuk-cdn-config/pull/17 and https://github.com/alphagov/govuk-cdn-config/pull/23).

A nicer way would be to have a YAML file like:

```yaml
ab_tests:
  - name: EducationNavigation
    b_percentage: 10%
  - name: Example
    b_percentage: 50%
```

We could take file file and generate the VCL, because it's all ERB anyway.
